### ISSUE TITLE
parse_order_book() missing 1 required positional argument: 'symbol'

### ISSUE THREAD

**Issue by davidtavarez** [binares/ccxt-unmerged#1]
Hi! I'm testing the TradeOgre support. It seems there's an issue here because I'm receiving this error from this line https://github.com/binares/ccxt-unmerged/blob/master/ccxt_unmerged/tradeogre.py#L181:

`parse_order_book() missing 1 required positional argument: 'symbol'`

Taking an example from the `ccxt` repo, it seems the correct manner should be like this:

`self.parse_order_book(orderbook, symbol, timestamp)`
(example https://github.com/ccxt/ccxt/blob/master/python/ccxt/gateio.py#L694)

Am I missing something? is that is correct I can open a PR at least for TradeOgre because it looks like that's the issue.

Thanks.

**Comment by binares** [comment]
thanks @davidtavarez, it seems that ccxt has changed the ccxt.Exchange.parse_order_book method from
```
def parse_order_book(self, orderbook, timestamp=None, bids_key='bids', asks_key='asks', price_key=0, amount_key=1)
```
to
```
# additional 'symbol' param
def parse_order_book(self, orderbook, symbol, timestamp=None, bids_key='bids', asks_key='asks', price_key=0, amount_key=1)
```
I'll update all the exchanges in this repo

**Comment by davidtavarez** [comment]
Thank you so much!! Pretty cool library btw 👍

**Comment by binares** [comment]
@davidtavarez you can now upgrade to v2.2 `pip install --upgrade ccxt-unmerged`
