### ISSUE TITLE
How to get 'cryptocom' derivatives 

### ISSUE THREAD

**Issue by ro-stack** [binares/ccxt-unmerged#2]
Hi, 
All works great so far, this is exactly what I've been looking for. The cryptocom works perfectly, however I am also trying to access derivatives from cryptocom which are not returned. I know Binance you need to declare 'options = {'defaultType': 'delivery', 'adjustForTimeDifference': True}' so was wondering if cryptocom required similar.
Or, if it requires a separate class.

**Comment by binares** [comment]
Hi @ro-stack, if u can implement a solution I can merge it.

**Comment by ro-stack** [comment]
@binares Happy to give it a go, but wouldn't know where to start, could you give me some pointers i.e. what distinguishes the cryptocom code of yours to what I would then require for cryptocom derivatives? The first difference I see is just the links included? I assume many methods would be similar

**Comment by binares** [comment]
Depending on exchange it can be as simple as changing url endpoints in sign() method, but if the responses are somewhat different then fetch_(), parse_() and other methods might have to be adjusted as well (as in Binance). I suggest you read the cryptocom docs and extrapolate from other exchange classes.

**Comment by ro-stack** [comment]
Had a go at trying to create cryptocom derivatives, the only change I could see was the api link which is correct, but from there I could not see where to go as many calls are exactly the same. An example being, calling fetch_tickers on cryptocom works fine, but when I try with the exact same code but the api link changed to the derivatives version it returns an invalid request.
They both share the same calls like - get-instruments, so hoped it would be a simple change, the only difference is 'deriv' added to the website name

**Comment by binares** [comment]
This works: https://deriv-api.crypto.com/v1/public/get-tickers

Derivatives docs: https://exchange-docs.crypto.com/derivatives

But this is all that I'm going to help :)
